-- Req 77: Gestión de Amenities (Servicios)

-- 1. Crear tabla de catálogo de amenidades
CREATE TABLE IF NOT EXISTS amenities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL DEFAULT 'Otros',
  icon_name TEXT, -- Nombre del icono de Lucide (ej: 'Wifi', 'Car')
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Habilitar RLS
ALTER TABLE amenities ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de seguridad
-- Todos pueden ver las amenidades
CREATE POLICY "Anyone can view amenities" ON amenities
  FOR SELECT
  USING (true);

-- Solo admins pueden gestionar amenidades
CREATE POLICY "Admins can manage amenities" ON amenities
  FOR ALL
  USING (
    auth.uid() IN (
      SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
    )
  );

-- 4. Insertar amenidades iniciales (Migración de hardcoded a DB)
INSERT INTO amenities (name, category, icon_name) VALUES
-- Tecnología
('WiFi', 'Tecnología', 'Wifi'),
('TV por cable', 'Tecnología', 'Tv'),
('Internet fibra óptica', 'Tecnología', 'Zap'),

-- Estacionamiento
('Estacionamiento', 'Estacionamiento', 'Car'),
('Parqueadero cubierto', 'Estacionamiento', 'Building'),
('Parqueadero visitantes', 'Estacionamiento', 'Users'),
('Garaje privado', 'Estacionamiento', 'Home'),

-- Seguridad
('Seguridad 24h', 'Seguridad', 'Shield'),
('Cámaras de seguridad', 'Seguridad', 'Cctv'),
('Control de acceso', 'Seguridad', 'Lock'),
('Portería', 'Seguridad', 'Users'),

-- Recreación
('Gimnasio', 'Recreación', 'Dumbbell'),
('Piscina', 'Recreación', 'Waves'),
('Piscina para niños', 'Recreación', 'Baby'),
('Cancha de tenis', 'Recreación', 'Activity'),
('Cancha de fútbol', 'Recreación', 'Gamepad2'),
('Cancha de baloncesto', 'Recreación', 'Activity'),
('Zona de juegos infantiles', 'Recreación', 'Baby'),
('Área para niños', 'Recreación', 'Baby'),
('Salón de juegos', 'Recreación', 'Gamepad2'),
('Salón de fiestas', 'Recreación', 'Music'),
('Zona de asados', 'Recreación', 'Flame'),

-- Zonas Verdes
('Jardín', 'Zonas Verdes', 'Trees'),
('Zonas verdes', 'Zonas Verdes', 'TreePine'),
('Terraza', 'Zonas Verdes', 'Building2'),
('Balcón', 'Zonas Verdes', 'Sun'),
('Jardín en azotea', 'Zonas Verdes', 'Flower'),
('Patio', 'Zonas Verdes', 'Fence'),

-- Servicios
('Ascensor', 'Servicios', 'ArrowUp'),
('Lavandería', 'Servicios', 'WashingMachine'),
('Servicio de limpieza', 'Servicios', 'Sparkles'),
('Mantenimiento', 'Servicios', 'Briefcase'),
('Conserjería', 'Servicios', 'Users'),

-- Mobiliario
('Amoblado', 'Mobiliario', 'Sofa'),
('Cocina equipada', 'Mobiliario', 'ChefHat'),
('Nevera', 'Mobiliario', 'Refrigerator'),
('Lavadora', 'Mobiliario', 'WashingMachine'),
('Secadora', 'Mobiliario', 'Shirt'),
('Lavavajillas', 'Mobiliario', 'Droplets'),

-- Clima
('Aire acondicionado', 'Clima', 'Wind'),
('Calefacción', 'Clima', 'Thermometer'),
('Ventilador de techo', 'Clima', 'Fan'),
('Iluminación natural', 'Clima', 'Lightbulb'),

-- Servicios Públicos
('Electricidad incluida', 'Servicios Públicos', 'Zap'),
('Agua incluida', 'Servicios Públicos', 'Droplets'),
('Gas incluido', 'Servicios Públicos', 'Flame'),
('Administración incluida', 'Servicios Públicos', 'FileText'),

-- Mascotas
('Acepta mascotas', 'Mascotas', 'Dog'),
('Área para perros', 'Mascotas', 'Dog'),
('Guardería de mascotas', 'Mascotas', 'Heart'),

-- Cercanías
('Supermercado cercano', 'Cercanías', 'ShoppingCart'),
('Centro comercial', 'Cercanías', 'ShoppingBag'),
('Colegios cercanos', 'Cercanías', 'GraduationCap'),
('Universidades', 'Cercanías', 'School'),
('Parques cercanos', 'Cercanías', 'Trees'),
('Transporte público', 'Cercanías', 'Bus'),
('Estación de metro/bus', 'Cercanías', 'Train'),
('Aeropuerto cercano', 'Cercanías', 'Plane'),
('Restaurantes', 'Cercanías', 'Utensils'),
('Hospitales', 'Cercanías', 'Activity')
ON CONFLICT (name) DO NOTHING;
