-- Req 71: Notas Internas de Propiedades

-- 1. Crear tabla de notas internas
CREATE TABLE IF NOT EXISTS property_internal_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT REFERENCES properties(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Índices
CREATE INDEX IF NOT EXISTS idx_internal_notes_property ON property_internal_notes(property_id);
CREATE INDEX IF NOT EXISTS idx_internal_notes_created_at ON property_internal_notes(created_at DESC);

-- 3. Habilitar RLS
ALTER TABLE property_internal_notes ENABLE ROW LEVEL SECURITY;

-- 4. Políticas de seguridad
-- Permitir lectura a admins y asesores
CREATE POLICY "Admins and Advisors can view internal notes" ON property_internal_notes
  FOR SELECT
  USING (
    auth.uid() IN (
      SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
      UNION
      SELECT id FROM public.advisors WHERE email = (SELECT email FROM auth.users WHERE id = auth.uid())
    )
  );

-- Permitir inserción a admins y asesores
CREATE POLICY "Admins and Advisors can insert internal notes" ON property_internal_notes
  FOR INSERT
  WITH CHECK (
    auth.uid() IN (
      SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
      UNION
      SELECT id FROM public.advisors WHERE email = (SELECT email FROM auth.users WHERE id = auth.uid())
    )
  );

-- Permitir borrado solo al autor o admins
CREATE POLICY "Users can delete their own notes or admins" ON property_internal_notes
  FOR DELETE
  USING (
    auth.uid() = created_by OR
    EXISTS (SELECT 1 FROM auth.users WHERE id = auth.uid() AND raw_user_meta_data->>'role' = 'admin')
  );
