-- Req 74: Gestión de precios históricos por propiedad

-- 1. Crear tabla de historial de precios
CREATE TABLE IF NOT EXISTS property_price_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT REFERENCES properties(id) ON DELETE CASCADE,
  price_type TEXT NOT NULL CHECK (price_type IN ('sale', 'rent')),
  old_price NUMERIC,
  new_price NUMERIC NOT NULL,
  changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  changed_by UUID REFERENCES auth.users(id)
);

-- 2. Índices para rendimiento
CREATE INDEX IF NOT EXISTS idx_price_history_property ON property_price_history(property_id);
CREATE INDEX IF NOT EXISTS idx_price_history_date ON property_price_history(changed_at DESC);

-- 3. Habilitar seguridad RLS
ALTER TABLE property_price_history ENABLE ROW LEVEL SECURITY;

-- 4. Políticas de seguridad (Solo lectura para admins y asesores)
CREATE POLICY "Admins and Advisors can view price history" ON property_price_history
  FOR SELECT
  USING (
    auth.uid() IN (
      SELECT id FROM auth.users WHERE raw_user_meta_data->>'role' = 'admin'
      UNION
      SELECT id FROM public.advisors WHERE email = (SELECT email FROM auth.users WHERE id = auth.uid())
    )
  );

-- 5. Función del Trigger para detectar cambios automáticamente
CREATE OR REPLACE FUNCTION log_property_price_change()
RETURNS TRIGGER AS $$
BEGIN
  -- Verificar cambio en precio de venta
  IF (NEW.sale_price IS DISTINCT FROM OLD.sale_price) THEN
    INSERT INTO property_price_history (property_id, price_type, old_price, new_price, changed_by)
    VALUES (NEW.id, 'sale', OLD.sale_price, NEW.sale_price, auth.uid());
  END IF;

  -- Verificar cambio en precio de arriendo
  IF (NEW.rent_price IS DISTINCT FROM OLD.rent_price) THEN
    INSERT INTO property_price_history (property_id, price_type, old_price, new_price, changed_by)
    VALUES (NEW.id, 'rent', OLD.rent_price, NEW.rent_price, auth.uid());
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Crear el Trigger en la tabla properties
DROP TRIGGER IF EXISTS on_property_price_change ON properties;
CREATE TRIGGER on_property_price_change
  AFTER UPDATE ON properties
  FOR EACH ROW
  EXECUTE FUNCTION log_property_price_change();
